sudo: resuired
language: node_js
node_js:
- '6'
env:
- CXX=g++-4.8
services:
- docker
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
os:
- linux

script:
- npm -g install babel-cli
- babel ./src -d /tmp/bin --minified --ignore 'node_modules/'
- docker build -t innovate/itframe:latest .

deploy:
  provider: script
  script: ./deploy.sh
  on:
    repo: innovate-technologies/itframe
    tags: true
    branch: master
