language: node_js
node_js:
- '4'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
os:
- linux

install:
- "npm install -g npm@^3"
- npm install 

script:
- ./node_modules/.bin/babel ./ -d bin --minified --ignore 'node_modules/'
