language: node_js
node_js:
- '5'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
os:
- linux

script:
- npm -g install babel-cli
- babel ./ -d bin --minified --ignore 'node_modules/'
